export default [
  {
    name: "Andorra",
    countryCode: "AD",
    dialCode: "+376",
    stateFieldRequired: false,
  },
  {
    name: "Antigua And Barbuda",
    countryCode: "AG",
    dialCode: "+1268",
    stateFieldRequired: false,
  },
  {
    name: "Anguilla",
    countryCode: "AI",
    dialCode: "+1 264",
    stateFieldRequired: false,
  },
  {
    name: "Albania",
    countryCode: "AL",
    dialCode: "+355",
    stateFieldRequired: false,
  },
  {
    name: "Armenia",
    countryCode: "AM",
    dialCode: "+374",
    stateFieldRequired: false,
  },
  {
    name: "Angola",
    countryCode: "AO",
    dialCode: "+244",
    stateFieldRequired: false,
  },
  {
    name: "Argentina",
    countryCode: "AR",
    dialCode: "+54",
    stateFieldRequired: false,
  },
  {
    name: "American Samoa",
    countryCode: "AS",
    dialCode: "+1 684",
    stateFieldRequired: false,
  },
  {
    name: "Austria",
    countryCode: "AT",
    dialCode: "+43",
    stateFieldRequired: false,
  },
  {
    name: "Australia",
    countryCode: "AU",
    dialCode: "+61",
    stateFieldRequired: false,
  },
  {
    name: "Aruba",
    countryCode: "AW",
    dialCode: "+297",
    stateFieldRequired: false,
  },
  {
    name: "Bosnia",
    countryCode: "BA",
    dialCode: "+387",
    stateFieldRequired: false,
  },
  {
    name: "Barbados",
    countryCode: "BB",
    dialCode: "+1 246",
    stateFieldRequired: false,
  },
  {
    name: "Bangladesh",
    countryCode: "BD",
    dialCode: "+880",
    stateFieldRequired: false,
  },
  {
    name: "Belgium",
    countryCode: "BE",
    dialCode: "+32",
    stateFieldRequired: false,
  },
  {
    name: "Burkina Faso",
    countryCode: "BF",
    dialCode: "+226",
    stateFieldRequired: false,
  },
  {
    name: "Bulgaria",
    countryCode: "BG",
    dialCode: "+359",
    stateFieldRequired: false,
  },
  {
    name: "Bahrain",
    countryCode: "BH",
    dialCode: "+973",
    stateFieldRequired: false,
  },
  {
    name: "Burundi",
    countryCode: "BI",
    dialCode: "+257",
    stateFieldRequired: false,
  },
  {
    name: "Bermuda",
    countryCode: "BM",
    dialCode: "+1 441",
    stateFieldRequired: false,
  },
  {
    name: "Bolivia",
    countryCode: "BO",
    dialCode: "+591",
    stateFieldRequired: false,
  },
  {
    name: "Brazil",
    countryCode: "BR",
    dialCode: "+55",
    stateFieldRequired: false,
  },
  {
    name: "Bahamas",
    countryCode: "BS",
    dialCode: "+1 242",
    stateFieldRequired: false,
  },
  {
    name: "Bhutan",
    countryCode: "BT",
    dialCode: "+975",
    stateFieldRequired: false,
  },
  {
    name: "Botswana",
    countryCode: "BW",
    dialCode: "+267",
    stateFieldRequired: false,
  },
  {
    name: "Belarus",
    countryCode: "BY",
    dialCode: "+375",
    stateFieldRequired: false,
  },
  {
    name: "Belize",
    countryCode: "BZ",
    dialCode: "+501",
    stateFieldRequired: false,
  },
  {
    name: "Canada",
    countryCode: "CA",
    dialCode: "+1",
    stateFieldRequired: true,
  },
  {
    name: "Canary Islands",
    countryCode: "IC",
    dialCode: "+34",
    stateFieldRequired: false,
  },
  {
    name: "Congo",
    countryCode: "CG",
    dialCode: "+242",
    stateFieldRequired: false,
  },
  {
    name: "Switzerland",
    countryCode: "CH",
    dialCode: "+41",
    stateFieldRequired: false,
  },
  {
    name: "Cote D'Ivoire",
    countryCode: "CI",
    dialCode: "+225",
    stateFieldRequired: false,
  },
  {
    name: "Cook Islands",
    countryCode: "CK",
    dialCode: "+682",
    stateFieldRequired: false,
  },
  {
    name: "Chile",
    countryCode: "CL",
    dialCode: "+56",
    stateFieldRequired: false,
  },
  {
    name: "Cameroon",
    countryCode: "CM",
    dialCode: "+237",
    stateFieldRequired: false,
  },
  {
    name: "China",
    countryCode: "CN",
    dialCode: "+86",
    stateFieldRequired: false,
  },
  {
    name: "Colombia",
    countryCode: "CO",
    dialCode: "+57",
    stateFieldRequired: false,
  },
  {
    name: "Costa Rica",
    countryCode: "CR",
    dialCode: "+506",
    stateFieldRequired: false,
  },
  {
    name: "Serbia",
    countryCode: "RS",
    dialCode: "+381",
    stateFieldRequired: false,
  },
  {
    name: "Cuba",
    countryCode: "CU",
    dialCode: "+53",
    stateFieldRequired: false,
  },
  {
    name: "Cape Verde",
    countryCode: "CV",
    dialCode: "+238",
    stateFieldRequired: false,
  },
  {
    name: "Cyprus",
    countryCode: "CY",
    dialCode: "+537",
    stateFieldRequired: false,
  },
  {
    name: "Czech Republic",
    countryCode: "CZ",
    dialCode: "+420",
    stateFieldRequired: false,
  },
  {
    name: "Germany",
    countryCode: "DE",
    dialCode: "+49",
    stateFieldRequired: false,
  },
  {
    name: "Denmark",
    countryCode: "DK",
    dialCode: "+45",
    stateFieldRequired: false,
  },
  {
    name: "Dominica",
    countryCode: "DM",
    dialCode: "+1 767",
    stateFieldRequired: false,
  },
  {
    name: "Dominican Republic",
    countryCode: "DO",
    dialCode: "+1 849",
    stateFieldRequired: false,
  },
  {
    name: "Algeria",
    countryCode: "DZ",
    dialCode: "+213",
    stateFieldRequired: false,
  },
  {
    name: "Ecuador",
    countryCode: "EC",
    dialCode: "+593",
    stateFieldRequired: false,
  },
  {
    name: "Estonia",
    countryCode: "EE",
    dialCode: "+372",
    stateFieldRequired: false,
  },
  {
    name: "Egypt",
    countryCode: "EG",
    dialCode: "+20",
    stateFieldRequired: false,
  },
  {
    name: "Eritrea",
    countryCode: "ER",
    dialCode: "+291",
    stateFieldRequired: false,
  },
  {
    name: "Spain",
    countryCode: "ES",
    dialCode: "+34",
    stateFieldRequired: false,
  },
  {
    name: "Ethiopia",
    countryCode: "ET",
    dialCode: "+251",
    stateFieldRequired: false,
  },
  {
    name: "Finland",
    countryCode: "FI",
    dialCode: "+358",
    stateFieldRequired: false,
  },
  {
    name: "Fiji",
    countryCode: "FJ",
    dialCode: "+679",
    stateFieldRequired: false,
  },
  {
    name: "Falkland Islands",
    countryCode: "FK",
    dialCode: "+500",
    stateFieldRequired: false,
  },
  {
    name: "Micronesia",
    countryCode: "FM",
    dialCode: "+691",
    stateFieldRequired: false,
  },
  {
    name: "Faroe Islands",
    countryCode: "FO",
    dialCode: "+298",
    stateFieldRequired: false,
  },
  {
    name: "France",
    countryCode: "FR",
    dialCode: "+33",
    stateFieldRequired: false,
  },
  {
    name: "Gabon",
    countryCode: "GA",
    dialCode: "+241",
    stateFieldRequired: false,
  },
  {
    name: "United Kingdom",
    countryCode: "GB",
    dialCode: "+44",
    stateFieldRequired: false,
  },
  {
    name: "Grenada",
    countryCode: "GD",
    dialCode: "+1 473",
    stateFieldRequired: false,
  },
  {
    name: "Georgia",
    countryCode: "GE",
    dialCode: "+995",
    stateFieldRequired: false,
  },
  {
    name: "French Guiana",
    countryCode: "GF",
    dialCode: "+594",
    stateFieldRequired: false,
  },
  {
    name: "Ghana",
    countryCode: "GH",
    dialCode: "+233",
    stateFieldRequired: false,
  },
  {
    name: "Gibraltar",
    countryCode: "GI",
    dialCode: "+350",
    stateFieldRequired: false,
  },
  {
    name: "Greenland",
    countryCode: "GL",
    dialCode: "+299",
    stateFieldRequired: false,
  },
  {
    name: "Gambia",
    countryCode: "GM",
    dialCode: "+220",
    stateFieldRequired: false,
  },
  {
    name: "Guinea",
    countryCode: "GN",
    dialCode: "+224",
    stateFieldRequired: false,
  },
  {
    name: "Guadeloupe",
    countryCode: "GP",
    dialCode: "+590",
    stateFieldRequired: false,
  },
  {
    name: "Equatorial Guinea",
    countryCode: "GQ",
    dialCode: "+240",
    stateFieldRequired: false,
  },
  {
    name: "Greece",
    countryCode: "GR",
    dialCode: "+30",
    stateFieldRequired: false,
  },
  {
    name: "Guatemala",
    countryCode: "GT",
    dialCode: "+502",
    stateFieldRequired: false,
  },
  {
    name: "Guam",
    countryCode: "GU",
    dialCode: "+1 671",
    stateFieldRequired: false,
  },
  {
    name: "Guinea-Bissau",
    countryCode: "GW",
    dialCode: "+245",
    stateFieldRequired: false,
  },
  {
    name: "Guyana",
    countryCode: "GY",
    dialCode: "+595",
    stateFieldRequired: false,
  },
  {
    name: "Hong Kong",
    countryCode: "HK",
    dialCode: "+852",
    stateFieldRequired: false,
  },
  {
    name: "Honduras",
    countryCode: "HN",
    dialCode: "+504",
    stateFieldRequired: false,
  },
  {
    name: "Croatia",
    countryCode: "HR",
    dialCode: "+385",
    stateFieldRequired: false,
  },
  {
    name: "Haiti",
    countryCode: "HT",
    dialCode: "+509",
    stateFieldRequired: false,
  },
  {
    name: "Hungary",
    countryCode: "HU",
    dialCode: "+36",
    stateFieldRequired: false,
  },
  {
    name: "Indonesia",
    countryCode: "ID",
    dialCode: "+62",
    stateFieldRequired: false,
  },
  {
    name: "Ireland",
    countryCode: "IE",
    dialCode: "+353",
    stateFieldRequired: false,
  },
  {
    name: "Israel",
    countryCode: "IL",
    dialCode: "+972",
    stateFieldRequired: false,
  },
  {
    name: "India",
    countryCode: "IN",
    dialCode: "+91",
    stateFieldRequired: false,
  },
  {
    name: "Iraq",
    countryCode: "IQ",
    dialCode: "+964",
    stateFieldRequired: false,
  },
  {
    name: "Iran",
    countryCode: "IR",
    dialCode: "+98",
    stateFieldRequired: false,
  },
  {
    name: "Iceland",
    countryCode: "IS",
    dialCode: "+354",
    stateFieldRequired: false,
  },
  {
    name: "Italy",
    countryCode: "IT",
    dialCode: "+39",
    stateFieldRequired: false,
  },
  {
    name: "Jamaica",
    countryCode: "JM",
    dialCode: "+1 876",
    stateFieldRequired: false,
  },
  {
    name: "Jordan",
    countryCode: "JO",
    dialCode: "+962",
    stateFieldRequired: false,
  },
  {
    name: "Japan",
    countryCode: "JP",
    dialCode: "+81",
    stateFieldRequired: false,
  },
  {
    name: "Kenya",
    countryCode: "KE",
    dialCode: "+254",
    stateFieldRequired: false,
  },
  {
    name: "Kyrgyzstan",
    countryCode: "KG",
    dialCode: "+996",
    stateFieldRequired: false,
  },
  {
    name: "Cambodia",
    countryCode: "KH",
    dialCode: "+855",
    stateFieldRequired: false,
  },
  {
    name: "Comoros",
    countryCode: "KM",
    dialCode: "+269",
    stateFieldRequired: false,
  },
  {
    name: "St Kitts And Nevis",
    countryCode: "KN",
    dialCode: "+1 869",
    stateFieldRequired: false,
  },
  {
    name: "Korea",
    countryCode: "KR",
    dialCode: "+82",
    stateFieldRequired: false,
  },
  {
    name: "Kuwait",
    countryCode: "KW",
    dialCode: "+965",
    stateFieldRequired: false,
  },
  {
    name: "Cayman Islands",
    countryCode: "KY",
    dialCode: "+ 345",
    stateFieldRequired: false,
  },
  {
    name: "Kazakhstan",
    countryCode: "KZ",
    dialCode: "+7 7",
    stateFieldRequired: false,
  },
  {
    name: "Lao",
    countryCode: "LA",
    dialCode: "+856",
    stateFieldRequired: false,
  },
  {
    name: "Lebanon",
    countryCode: "LB",
    dialCode: "+961",
    stateFieldRequired: false,
  },
  {
    name: "St Lucia",
    countryCode: "LC",
    dialCode: "+1 758",
    stateFieldRequired: false,
  },
  {
    name: "Liechtenstein",
    countryCode: "LI",
    dialCode: "+423",
    stateFieldRequired: false,
  },
  {
    name: "Sri Lanka",
    countryCode: "LK",
    dialCode: "+94",
    stateFieldRequired: false,
  },
  {
    name: "Liberia",
    countryCode: "LR",
    dialCode: "+231",
    stateFieldRequired: false,
  },
  {
    name: "Lesotho",
    countryCode: "LS",
    dialCode: "+266",
    stateFieldRequired: false,
  },
  {
    name: "Lithuania",
    countryCode: "LT",
    dialCode: "+370",
    stateFieldRequired: false,
  },
  {
    name: "Luxembourg",
    countryCode: "LU",
    dialCode: "+352",
    stateFieldRequired: false,
  },
  {
    name: "Latvia",
    countryCode: "LV",
    dialCode: "+371",
    stateFieldRequired: false,
  },
  {
    name: "Morocco",
    countryCode: "MA",
    dialCode: "+212",
    stateFieldRequired: false,
  },
  {
    name: "Monaco",
    countryCode: "MC",
    dialCode: "+377",
    stateFieldRequired: false,
  },
  {
    name: "Moldova",
    countryCode: "MD",
    dialCode: "+373",
    stateFieldRequired: false,
  },
  {
    name: "Madagascar",
    countryCode: "MG",
    dialCode: "+261",
    stateFieldRequired: false,
  },
  {
    name: "Macedonia",
    countryCode: "MK",
    dialCode: "+389",
    stateFieldRequired: false,
  },
  {
    name: "Mali",
    countryCode: "ML",
    dialCode: "+223",
    stateFieldRequired: false,
  },
  {
    name: "Macau",
    countryCode: "MO",
    dialCode: "+853",
    stateFieldRequired: false,
  },
  {
    name: "Martinique",
    countryCode: "MQ",
    dialCode: "+596",
    stateFieldRequired: false,
  },
  {
    name: "Mauritania",
    countryCode: "MR",
    dialCode: "+222",
    stateFieldRequired: false,
  },
  {
    name: "Montserrat",
    countryCode: "MS",
    dialCode: "+1664",
    stateFieldRequired: false,
  },
  {
    name: "Malta",
    countryCode: "MT",
    dialCode: "+356",
    stateFieldRequired: false,
  },
  {
    name: "Mauritius",
    countryCode: "MU",
    dialCode: "+230",
    stateFieldRequired: false,
  },
  {
    name: "Maldives",
    countryCode: "MV",
    dialCode: "+960",
    stateFieldRequired: false,
  },
  {
    name: "Malawi",
    countryCode: "MW",
    dialCode: "+265",
    stateFieldRequired: false,
  },
  {
    name: "Mexico",
    countryCode: "MX",
    dialCode: "+52",
    stateFieldRequired: false,
  },
  {
    name: "Malaysia",
    countryCode: "MY",
    dialCode: "+60",
    stateFieldRequired: false,
  },
  {
    name: "Mozambique",
    countryCode: "MZ",
    dialCode: "+258",
    stateFieldRequired: false,
  },
  {
    name: "Namibia",
    countryCode: "NA",
    dialCode: "+264",
    stateFieldRequired: false,
  },
  {
    name: "New Caledonia",
    countryCode: "NC",
    dialCode: "+687",
    stateFieldRequired: false,
  },
  {
    name: "Niger",
    countryCode: "NE",
    dialCode: "+227",
    stateFieldRequired: false,
  },
  {
    name: "Nigeria",
    countryCode: "NG",
    dialCode: "+234",
    stateFieldRequired: false,
  },
  {
    name: "Nicaragua",
    countryCode: "NI",
    dialCode: "+505",
    stateFieldRequired: false,
  },
  {
    name: "Netherlands",
    countryCode: "NL",
    dialCode: "+31",
    stateFieldRequired: false,
  },
  {
    name: "Norway",
    countryCode: "NO",
    dialCode: "+47",
    stateFieldRequired: false,
  },
  {
    name: "Nepal",
    countryCode: "NP",
    dialCode: "+977",
    stateFieldRequired: false,
  },
  {
    name: "New Zealand",
    countryCode: "NZ",
    dialCode: "+64",
    stateFieldRequired: false,
  },
  {
    name: "Oman",
    countryCode: "OM",
    dialCode: "+968",
    stateFieldRequired: false,
  },
  {
    name: "Panama",
    countryCode: "PA",
    dialCode: "+507",
    stateFieldRequired: false,
  },
  {
    name: "Peru",
    countryCode: "PE",
    dialCode: "+51",
    stateFieldRequired: false,
  },
  {
    name: "French Polynesia",
    countryCode: "PF",
    dialCode: "+689",
    stateFieldRequired: false,
  },
  {
    name: "Papua New Guinea",
    countryCode: "PG",
    dialCode: "+675",
    stateFieldRequired: false,
  },
  {
    name: "Philippines",
    countryCode: "PH",
    dialCode: "+63",
    stateFieldRequired: false,
  },
  {
    name: "Pakistan",
    countryCode: "PK",
    dialCode: "+92",
    stateFieldRequired: false,
  },
  {
    name: "Poland",
    countryCode: "PL",
    dialCode: "+48",
    stateFieldRequired: false,
  },
  {
    name: "Pitcairn",
    countryCode: "PN",
    dialCode: "+872",
    stateFieldRequired: false,
  },
  {
    name: "Puerto Rico",
    countryCode: "PR",
    dialCode: "+1 939",
    stateFieldRequired: false,
  },
  {
    name: "Palestinian",
    countryCode: "PS",
    dialCode: "+970",
    stateFieldRequired: false,
  },
  {
    name: "Portugal",
    countryCode: "PT",
    dialCode: "+351",
    stateFieldRequired: false,
  },
  {
    name: "Paraguay",
    countryCode: "PY",
    dialCode: "+595",
    stateFieldRequired: false,
  },
  {
    name: "Qatar",
    countryCode: "QA",
    dialCode: "+974",
    stateFieldRequired: false,
  },
  {
    name: "Romania",
    countryCode: "RO",
    dialCode: "+40",
    stateFieldRequired: false,
  },
  {
    name: "Russian Federation",
    countryCode: "RU",
    dialCode: "+7",
    stateFieldRequired: false,
  },
  {
    name: "Rwanda",
    countryCode: "RW",
    dialCode: "+250",
    stateFieldRequired: false,
  },
  {
    name: "Saudi Arabia",
    countryCode: "SA",
    dialCode: "+966",
    stateFieldRequired: false,
  },
  {
    name: "Seychelles",
    countryCode: "SC",
    dialCode: "+248",
    stateFieldRequired: false,
  },
  {
    name: "Sudan",
    countryCode: "SD",
    dialCode: "+249",
    stateFieldRequired: false,
  },
  {
    name: "Sweden",
    countryCode: "SE",
    dialCode: "+46",
    stateFieldRequired: false,
  },
  {
    name: "Singapore",
    countryCode: "SG",
    dialCode: "+65",
    stateFieldRequired: false,
  },
  {
    name: "St Helena",
    countryCode: "SH",
    dialCode: "+290",
    stateFieldRequired: false,
  },
  {
    name: "Slovenia",
    countryCode: "SI",
    dialCode: "+386",
    stateFieldRequired: false,
  },
  {
    name: "Slovakia",
    countryCode: "SK",
    dialCode: "+421",
    stateFieldRequired: false,
  },
  {
    name: "Sierra Leone",
    countryCode: "SL",
    dialCode: "+232",
    stateFieldRequired: false,
  },
  {
    name: "San Marino",
    countryCode: "SM",
    dialCode: "+378",
    stateFieldRequired: false,
  },
  {
    name: "Senegal",
    countryCode: "SN",
    dialCode: "+221",
    stateFieldRequired: false,
  },
  {
    name: "Somalia",
    countryCode: "SO",
    dialCode: "+252",
    stateFieldRequired: false,
  },
  {
    name: "El Salvador",
    countryCode: "SV",
    dialCode: "+503",
    stateFieldRequired: false,
  },
  {
    name: "Syria",
    countryCode: "SY",
    dialCode: "+963",
    stateFieldRequired: false,
  },
  {
    name: "Swaziland",
    countryCode: "SZ",
    dialCode: "+268",
    stateFieldRequired: false,
  },
  {
    name: "Turks And Caicos",
    countryCode: "TC",
    dialCode: "+1 649",
    stateFieldRequired: false,
  },
  {
    name: "Chad",
    countryCode: "TD",
    dialCode: "+235",
    stateFieldRequired: false,
  },
  {
    name: "Thailand",
    countryCode: "TH",
    dialCode: "+66",
    stateFieldRequired: false,
  },
  {
    name: "Tajikistan",
    countryCode: "TJ",
    dialCode: "+992",
    stateFieldRequired: false,
  },
  {
    name: "Tunisia",
    countryCode: "TN",
    dialCode: "+216",
    stateFieldRequired: false,
  },
  {
    name: "Tonga",
    countryCode: "TO",
    dialCode: "+676",
    stateFieldRequired: false,
  },
  {
    name: "Turkey",
    countryCode: "TR",
    dialCode: "+90",
    stateFieldRequired: false,
  },
  {
    name: "Trinidad And Tobago",
    countryCode: "TT",
    dialCode: "+1 868",
    stateFieldRequired: false,
  },
  {
    name: "Taiwan",
    countryCode: "TW",
    dialCode: "+886",
    stateFieldRequired: false,
  },
  {
    name: "Tanzania",
    countryCode: "TZ",
    dialCode: "+255",
    stateFieldRequired: false,
  },
  {
    name: "Ukraine",
    countryCode: "UA",
    dialCode: "+380",
    stateFieldRequired: false,
  },
  {
    name: "Uganda",
    countryCode: "UG",
    dialCode: "+256",
    stateFieldRequired: false,
  },
  { name: "USA", countryCode: "US", dialCode: "+1", stateFieldRequired: true },
  {
    name: "Uruguay",
    countryCode: "UY",
    dialCode: "+598",
    stateFieldRequired: false,
  },
  {
    name: "Uzbekistan",
    countryCode: "UZ",
    dialCode: "+998",
    stateFieldRequired: false,
  },
  {
    name: "Vatican City",
    countryCode: "VA",
    dialCode: "+379",
    stateFieldRequired: false,
  },
  {
    name: "St Vincent",
    countryCode: "VC",
    dialCode: "+1 784",
    stateFieldRequired: false,
  },
  {
    name: "Venezuela",
    countryCode: "VE",
    dialCode: "+58",
    stateFieldRequired: false,
  },
  {
    name: "Virgin Islands",
    countryCode: "VG",
    dialCode: "+1 284",
    stateFieldRequired: false,
  },
  {
    name: "Vietnam",
    countryCode: "VN",
    dialCode: "+84",
    stateFieldRequired: false,
  },
  {
    name: "Samoa",
    countryCode: "WS",
    dialCode: "+685",
    stateFieldRequired: false,
  },
  {
    name: "Yemen",
    countryCode: "YE",
    dialCode: "+967",
    stateFieldRequired: false,
  },
  {
    name: "South Africa",
    countryCode: "ZA",
    dialCode: "+27",
    stateFieldRequired: false,
  },
  {
    name: "Zambia",
    countryCode: "ZM",
    dialCode: "+260",
    stateFieldRequired: false,
  },
  {
    name: "Zimbabwe",
    countryCode: "ZW",
    dialCode: "+263",
    stateFieldRequired: false,
  },
  {
    name: "Guernsey (C.I.)",
    countryCode: "GG",
    dialCode: "+44",
    stateFieldRequired: false,
  },
  {
    name: "Jersey (C.I.)",
    countryCode: "JE",
    dialCode: "+44",
    stateFieldRequired: false,
  },
  {
    name: "Azerbaijan",
    countryCode: "AZ",
    dialCode: "+994",
    stateFieldRequired: false,
  },
  {
    name: "Réunion",
    countryCode: "RE",
    dialCode: "+262",
    stateFieldRequired: false,
  },
  {
    name: "UAE",
    countryCode: "AE",
    dialCode: "+971",
    stateFieldRequired: false,
  },
];
